name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]  # Must match the "name:" in your build.yml EXACTLY
    types:
      - completed

jobs:
  deploy:
    if: ${{ 
      github.event.workflow_run.conclusion == 'success' && (
        github.event.workflow_run.event == 'push' && 
        github.event.workflow_run.head_branch == 'main'
      )
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        env:
          SECRET: ${{ secrets.WEBHOOK_SECRET }}
          URL: ${{ secrets.WEBHOOK_URL }}
          PAYLOAD: '{"repository": {"full_name":"${{ github.repository }}"}}'
        run: |
          SIG=$(echo -n "$PAYLOAD" \
            | openssl dgst -sha256 -hmac "$SECRET" \
            | sed 's/^.* //')

          curl -X POST $URL \
            -H "X-Hub-Signature-256: sha256=$SIG" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD"
